### ISSUE TITLE
Undocumented Error Code

### ISSUE THREAD

**Issue by vpetkovic** [viceroypenguin/Going.Plaid.NET#24]
Hey @viceroypenguin, great work! 

While poking around I mistakenly removed a character from a non required property while trying to create a link token, which haven't returned "UNKNOWN_FIELDS" or "INVALID_BODY" error code and have failed to [deserialize bad request response into PlaidException object](https://github.com/viceroypenguin/Going.Plaid.NET/blob/02c2cb20abf7eff6198007f8831145be0bf98cdc/src/Plaid/PlaidClient.cs#L377) with a message `Unexpected token INVALID_CONFIGURATION when parsing enum`.

I have looked into API docs but haven't found any reference of that error code "INVALID_CONFIGURATION" but it exists. 

Response Body:
 
    {
        "display_message": null,
        "documentation_url": "https://plaid.com/docs/#create-link-token",
        "error_code": "INVALID_CONFIGURATION",
        "error_message": "please ensure that the request body is formatted correctly",
        "error_type": "INVALID_REQUEST",
        "request_id": "DRz6S8z08wiveMz"
    }

**Comment by viceroypenguin** [comment]
Sure enough! No reference to it on the website. You should file a comment w/ them to update their documentation for it. That said, take a look at the PR (#25) for a second set of eyes? Then I'll pull it in and release a v2.3.1 for ya.

**Comment by vpetkovic** [comment]
Yep already did let them know. Thanks for quick fix again. 🤘

**Comment by viceroypenguin** [comment]
Sure! Glad to help. 😊
