### ISSUE TITLE
JsonPropertyName("account_ids") required on AccountOptions.AccountIds

### ISSUE THREAD

**Issue by SteveMcGuire1** [viceroypenguin/Going.Plaid.NET#26]
GetAccountInfoRequest() has the property Options that can be used to filter the accounts returned but this does not work because we get the error: "the following fields are not recognized by this endpoint: options.AccountIds" which I presume is because the property needs the JsonPropertyNameAttribute set?

**Comment by viceroypenguin** [comment]
Sure enough, somehow I missed that. Do you want to create a PR for it, or I can fix it up real quick? Up to you!

**Comment by SteveMcGuire1** [comment]
Beat me to it, thanks! 👍

**Comment by viceroypenguin** [comment]
Released under v2.3.2
