### ISSUE TITLE
PlaidOptions Environment in Development sending requests to sandbox

### ISSUE THREAD

**Issue by jphgardner** [viceroypenguin/Going.Plaid.NET#30]
Hi,

Just encountering an issue now I have development access to plaid.

Setting this to development, does not make the PlaidClient use development plaid url.

![image](https://user-images.githubusercontent.com/226000/107793404-288ae500-6d4e-11eb-92fd-ca1c0bb5f41c.png)

**Comment by viceroypenguin** [comment]
First, a nitpick. Please be careful posting a screenshot like this, since your clientid and secret are both in the picture, and can be scraped by someone for nefarious purposes. In fact, you should now go to Plaid and rotate your Development key for security.

**Comment by jphgardner** [comment]
@viceroypenguin Good spot, sorry about that, I have rotated them and removed the image

**Comment by viceroypenguin** [comment]
Seeing this, I notice that the client id and secret are also not being provided to `PlaidClient`. You are using `services.Configure<PlaidOptions>(section)`, which is using the values as written in the configuration, not the values that you have put into `plaidOptions` variable. I would do the following:
* Check that the `.Bind()` is properly transferring values to `plaidOptions`
* Change the configure line to `services.AddSingleton(plaidOptions)`, so that you are storing a specific instance (i.e. the one you created with values as you like) into the DI system rather than forcing them to be recreated.

**Comment by jphgardner** [comment]
Thanks ill try that now

**Comment by jphgardner** [comment]
So I have injected IOptions<PlaidOptions> into my controller and thte environment is set to 2, which is wrong. 

This means my code for setting the environment property based on the hosting environment is not working properly.

The bind is working correctly and is transferring the clientId and secret to the PlaidOptions class

**Comment by viceroypenguin** [comment]
Environment = 2 (Environment.Development) sounds correct? Default is Environment.Sandbox (1), so the fact that you have 2 means you're changing something, and saving it to the DI properly, I think. Unless I'm misreading something.

**Comment by jphgardner** [comment]
Right okay, in which case why is the requests going to sandbox?

**Comment by jphgardner** [comment]
Enums start at 0 it seems.. so environment = 2 is actually sandbox

![image](https://user-images.githubusercontent.com/226000/107796625-fda29000-6d51-11eb-8148-3e6bd2e2f12c.png)
![image](https://user-images.githubusercontent.com/226000/107796680-0b581580-6d52-11eb-9eb5-8796ab87a29b.png)

**Comment by viceroypenguin** [comment]
Oh. Sorry. I forgot my own code. 😄

**Comment by viceroypenguin** [comment]
Let's try this:
```csharp
var section = configuration.GetSection(...);
if (IsDevelopment())
  section["Environment"] = nameof(Environment.Development);
else if (IsProduction())
  section["Environment"] = nameof(Environment.Production);
services.Configure<PlaidOptions>(section);
services.AddSingleton<PlaidClient>();
```

Upon consideration, I think the DI won't take an actual PlaidOptions, it wants it done via `Configure<>()` to generate an `IOptions<PlaidOptions>`. So give it one w/ the section modified appropriately. 

Your other option is to use the delegate form to pass in the known values and resolve the `clientFactory` and `logger` from the provided resolver.

**Comment by jphgardner** [comment]
Legend thats worked! thanks man

**Comment by viceroypenguin** [comment]
Great! Glad I could help!
