### ISSUE TITLE
Transaction Entity Missing properties

### ISSUE THREAD

**Issue by jphgardner** [viceroypenguin/Going.Plaid.NET#33]
Hi mate,

Looks like the transaction entity is missing properties
![image](https://user-images.githubusercontent.com/226000/111706412-28dd3b00-883a-11eb-8768-0885c906ecaa.png)

https://plaid.com/docs/api/products/#transactions-get-response-transactions

**Comment by viceroypenguin** [comment]
Which version are you using? I just looked, and in the current version (v2.4.0), every field that is squiggled in your picture is present. Or are there other fields that you need?

**Comment by jphgardner** [comment]
Im using 2.4.0, There isnt any payment meta or merchant name, or transaction code, currently there isnt a way to distinguish direct debits from a transaction because of this

**Comment by viceroypenguin** [comment]
PR #34 created to address. Should do new release by EOD Monday

**Comment by viceroypenguin** [comment]
Released v2.4.1. Let me know if you need anything else!
