### ISSUE TITLE
The JSON value could not be converted to System.Nullable[Going.Plaid.Entity.AccountType]

### ISSUE THREAD

**Issue by mcpherson-enterprises** [viceroypenguin/Going.Plaid.NET#35]
I'm using the example code to implement a connection to Plaid using link. I have a controller that takes the OnSuccessMetadata object as input:

```csharp
[HttpPost]
        public async Task<bool> GetAccessToken([FromBody] OnSuccessMetadata input)
        {
//some code
        }
```

On the client side, I'm posting the following object to this controller:

```json
{
  "institution": {
    "name": "Bank of America",
    "institution_id": "ins_127989"
  },
  "account": {
    "id": "EeBoV84X86IboNKXvKobiRBD49ydzgij6wn47",
    "name": "Plaid Checking",
    "type": "depository",
    "subtype": "checking",
    "mask": "0000"
  },
  "account_id": "EeBoV84X86IboNKXvKobiRBD49ydzgij6wn47",
  "accounts": [
    {
      "id": "EeBoV84X86IboNKXvKobiRBD49ydzgij6wn47",
      "name": "Plaid Checking",
      "mask": "0000",
      "type": "depository",
      "subtype": "checking"
    }
  ],
  "link_session_id": "390a3594-214e-4e96-be2e-29a64dc7f64e",
  "public_token": "public-sandbox-70ffcb74-d1a1-4dcc-9f55-d04c4dab406e"
}
```

The response is an error
```json
{
	"error": {
		"code": 0,
		"message": "Your request is not valid!",
		"details": "The following errors were detected during validation.\r\n - The JSON value could not be converted to System.Nullable`1[Going.Plaid.Entity.AccountType]. Path: $.accounts[0].type | LineNumber: 0 | BytePositionInLine: 376.\r\n",
		"validationErrors": [
			{
				"message": "The JSON value could not be converted to System.Nullable'1[Going.Plaid.Entity.AccountType]. Path: $.accounts[0].type | LineNumber: 0 | BytePositionInLine: 376.",
				"members": [
					"$.accounts[0].type"
				]
			}
		]
	}
}
```

It appears that the AccountType is an enum, but the value returned from Plaid is a string. Unless I'm missing something, that is probably the cause of this error. Can the AccountType be changed to a string type rather than enum to accommodate this difference in the Plaid API?

**Comment by viceroypenguin** [comment]
I believe the issue is the `depository` vs `Depository`. For some reason, I had never added `[EnumMember]` attributes to the `AccountType` enum, but it still worked for the other objects where `AccountType` is used. I've added those to the enum in PR #36. 

@mcpherson-enterprises I've done a preliminary release as version 2.4.2-preview (a pre-release version). Can you test with that version and see if it fixes your issue? Thanks!

**Comment by mcpherson-enterprises** [comment]
Hi, thanks for the quick response. I updated to that preview release, but no dice. I get the same error. When I look at the AccountType, it still is an enum, and I don't see the [EnumMember] attribute added.

**Comment by viceroypenguin** [comment]
Apologies, I was totally looking at the wrong thing. Though adding `[EnumMember]` to the enum values of `AccountType` is useful, that wasn't what was having an impact on parsing this.

There is a custom converter, `Going.Plaid.Converters.EnumConverterFactory` that will tell `System.Text.Json` how to parse nullable enums. The serializers that Going.Plaid uses internally use this converter properly, but the default one for asp.net won't know how to do that (and `System.Text.Json` doesn't know about nullable enums by default). 

To register this converter w/ the default asp.net json serializer, update to 2.4.2-preview2 and add the following in your `ConfigureServices()` method:
```csharp
			services.Configure<JsonOptions>(o =>
			{
				o.SerializerOptions.Converters.Add(new Going.Plaid.Converters.EnumConverterFactory());
			});
```

I may consider adding this to the `services.AddPlaid()` call, but I'm hesitant to modify json settings globally when they may have their own json configuration, so I'll recommend you add this in your configuration for now.

**Comment by mcpherson-enterprises** [comment]
Still nothing. I'm using aspnetboilerplate, which has a modular structure; so I may have to try that code in one of the module classes. I'll figure out how to do that, unless you have any pointers..

**Comment by viceroypenguin** [comment]
According to aspnetboilerplate#3453, you should use `services.PostConfigure()` specifically. That said, I've never worked with ABP, so configuring json serialization options is beyond my direct expertise here.

**Comment by mcpherson-enterprises** [comment]
I was able to get it working by using that snippet you provided in my Startup.cs. I just had it in a place where it would never be executed; that's why it didn't work last time. Thanks for your help! What's the timeline for this pre-release getting formally released?

**Comment by viceroypenguin** [comment]
v2.5.0 has been released to Nuget! :)

**Comment by joshuakeel** [comment]
I ran into a similar issue where my `AccountType` `enum` values were getting serialized by the controller as type `int` instead of `string` (e.g. `0` vs. `depository`). For some reason, I couldn't get the instructions on configuring `JsonOptions` to work:

```C#
services.Configure<JsonOptions>(o =>
{
	o.SerializerOptions.Converters.Add(new Going.Plaid.Converters.EnumConverterFactory());
});
```

Specifically, the `o.SerializerOptions...` line was never hit in the debugger.

Instead, I had to do the following in my `Program` class:

```C#
builder.Services.AddControllers().AddJsonOptions(options =>
{
    options.JsonSerializerOptions.AddPlaidConverters();
});
```

I'm on a .NET 6 app, right out of the box, created by Visual Studio for Mac.

Hopefully this helps someone else who may run into the same issue. I'm sure there's a good explanation for why the other version doesn't work for me, but at least this one does!

**Comment by viceroypenguin** [comment]
Thanks for the update! I would guess that different versions of asp.net is the reason here - they've updated how different things are configured in asp.net core 3.1, asp.net 5, and asp.net 6. I'm glad you were able to figure it out!
