### ISSUE TITLE
WebhookResponse.cs is missing in this repo

### ISSUE THREAD

**Issue by raj4all** [viceroypenguin/Going.Plaid.NET#8]
The Ackara Plaid.Net repo has the [WebhookResponse ](https://github.com/Ackara/Plaid.NET/blob/master/src/Plaid/Management/WebhookResponse.cs)class. but its missing in this repo.
Can you please add it back?

https://github.com/Ackara/Plaid.NET/blob/master/src/Plaid/Management/WebhookResponse.cs

**Comment by viceroypenguin** [comment]
It doesn't appear that class was being used in Ackara's repo, which is why it was removed. The `item/webhook/update` API call (`PlaidClient.UpdateWebhookAsync()`) uses `UpdateWebhookRequest` and `UpdateWebhookResponse` classes. 

It can be added back if there is a specific purpose for it? Thanks.

**Comment by raj4all** [comment]
`UpdateWebhookRequest`, `UpdateWebhookResponses` are of different purpose. It is used when client app wants to update webhook url for a particular item.

`WebhookResponse` that I am asking for is for transaction updates. Plaid notify clientApps when any new transactions are identified by Plaid, any transactions got removed by Bank & for regular `historical, initial, default` updates. 

**Ref:** plaid.com/docs/#transactions-webhooks

**Comment by viceroypenguin** [comment]
Ah. I missed that. I'll add it this morning!

**Comment by raj4all** [comment]
Thank you !

> Ah. I missed that. I'll add it this morning!

**Comment by viceroypenguin** [comment]
Checkout `WebhookPayload` class in v1.2.0. Let me know if there's anything I'm missing!

**Comment by raj4all** [comment]
Sure, thanks!

> Checkout `WebhookPayload` class in v1.2.0. Let me know if there's anything I'm missing!
